post_max_size = 40M
upload_max_filesize = 40M
date.timezone="Europe/Moscow"
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

memory_limit=512M

# Opcache
opcache.enable=1
opcache.enable_cli=1

# Xdebug
xdebug.mode=develop
